controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

login_check:
    path: /login_check

oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
